### PR TITLE
Add debugger support

### PR DESCRIPTION
**Pull request by shashkambh**
This worked on my laptop, so it should work on any Debian based Linux distro, but I'm not 100% sure of that. Maybe test somewhere else if you can.

I don't have a mac, so I didn't modify the mac install script to install the dependencies. I assume they're on homebrew, but I'm not sure.

### CODE REVIEW

**Comment by jishminor** [comment]
Thanks for working on this. I have an Ubuntu machine I can test it on. I'll let you know the results and merge if this works successfully.

**Review by kirmani — COMMENTED** [review]
This is cool! Thanks for adding the install for openocd. This probably would have been a more systematic way to debug than printing to the LCD like we did...

**Comment by shashkambh** [comment]
Forgot to mention that you need to close openocd when you're done by running `sudo pkill openocd`. Sorry about that.

**Review by kirmani — APPROVED** [review]

**Review by jishminor — APPROVED** [review]
LGTM

**Pull request merged**
